# Resources:
# - Mage Server
# - Storage
# - Executers
# AWS_REGION: ...
# CONTAINER_NAME: ...
# ECR_REPOSITORY: ...
# ECS_CLUSTER: ...
# ECS_SERVICE: ...
# ECS_TASK_DEFINITION: ...

# 

# - Elastic Container Service (ECS):
#   - ...


# - Application Load Balancer (ALB):
#   - ...
output "alb_dns" {
  description = "The DNS of the mage server."
  value =  aws_alb.application_load_balancer.dns_name
}

# - Elastic File System (EFS):
#   - ...


# - Relational Database Service (RDS):
#   - ...
output "postgres_database" {
  value = aws_db_instance.rds.address
}